apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # staging
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    # production
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pierangelo1982@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: "nginx"
            #class: "traefik"